import { Holding } from './types';

// The exact portfolio extracted from the user's screenshots (Total Value: ₹37,69,158.10)
export const CURRENT_PORTFOLIO_HOLDINGS: Holding[] = [
  {
    id: 'midwest',
    symbol: 'MIDWEST',
    name: 'Midwest Gold Ltd',
    sector: 'Metals & Mining',
    marketCap: 'Small',
    investedAmount: 37800,
    currentValue: 2249790,
    aiScore: 52,
    peRatio: 142.5,
    pbRatio: 12.8,
    beta: 1.45,
    notes: 'Outlier 58x multibagger! Generates 97% of total rupee profits, creating extreme 59.7% concentration risk.'
  },
  {
    id: 'sbin',
    symbol: 'SBIN',
    name: 'State Bank of India',
    sector: 'Banking & Financials',
    marketCap: 'Large',
    investedAmount: 108358,
    currentValue: 168269,
    aiScore: 64,
    peRatio: 10.8,
    pbRatio: 1.5,
    beta: 1.15,
    notes: 'Strong PSU banking compounder with steady ROE and loan growth.'
  },
  {
    id: 'bhartiartl',
    symbol: 'BHARTIARTL',
    name: 'Bharti Airtel Ltd',
    sector: 'Telecommunications',
    marketCap: 'Large',
    investedAmount: 84631,
    currentValue: 141866,
    aiScore: 67,
    peRatio: 48.2,
    pbRatio: 5.6,
    beta: 0.78,
    notes: 'Consistent ARPU expansion and market share gains in telecom duopoly.'
  },
  {
    id: 'icicibank',
    symbol: 'ICICIBANK',
    name: 'ICICI Bank Ltd',
    sector: 'Banking & Financials',
    marketCap: 'Large',
    investedAmount: 103020,
    currentValue: 141790,
    aiScore: 66,
    peRatio: 17.5,
    pbRatio: 2.8,
    beta: 1.05,
    notes: 'Premier private lender with pristine asset quality and high NIMs.'
  },
  {
    id: 'lt',
    symbol: 'LT',
    name: 'Larsen & Toubro Ltd',
    sector: 'Capital Goods & Infra',
    marketCap: 'Large',
    investedAmount: 109800,
    currentValue: 141300,
    aiScore: 64,
    peRatio: 34.1,
    pbRatio: 4.2,
    beta: 0.92,
    notes: 'Record order book across domestic infrastructure and Middle East energy projects.'
  },
  {
    id: 'maruti',
    symbol: 'MARUTI',
    name: 'Maruti Suzuki India',
    sector: 'Automobile',
    marketCap: 'Large',
    investedAmount: 104500,
    currentValue: 126280,
    aiScore: 65,
    peRatio: 27.4,
    pbRatio: 4.1,
    beta: 0.85,
    notes: 'Dominant passenger vehicle franchise expanding hybrid and SUV portfolio.'
  },
  {
    id: 'reliance',
    symbol: 'RELIANCE',
    name: 'Reliance Industries',
    sector: 'Conglomerate & Energy',
    marketCap: 'Large',
    investedAmount: 123360,
    currentValue: 122976,
    aiScore: 63,
    peRatio: 25.1,
    pbRatio: 2.1,
    beta: 0.82,
    notes: 'Flagship conglomerate flat over holding period; telecom/retail spin-off catalysts.'
  },
  {
    id: 'hal',
    symbol: 'HAL',
    name: 'Hindustan Aeronautics Ltd',
    sector: 'Defense & Aerospace',
    marketCap: 'Large',
    investedAmount: 91680,
    currentValue: 120168,
    aiScore: 72,
    peRatio: 36.8,
    pbRatio: 7.4,
    beta: 1.22,
    notes: 'High indigenisation tailwinds and long-term multi-year defense delivery pipeline.'
  },
  {
    id: 'sunpharma',
    symbol: 'SUNPHARMA',
    name: 'Sun Pharmaceutical Ltd',
    sector: 'Healthcare & Pharma',
    marketCap: 'Large',
    investedAmount: 48720,
    currentValue: 78477,
    aiScore: 68,
    peRatio: 38.2,
    pbRatio: 5.1,
    beta: 0.55,
    notes: 'Defensive compounder with strong specialty franchise in US and India.'
  },
  {
    id: 'hdfcbank',
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Ltd',
    sector: 'Banking & Financials',
    marketCap: 'Large',
    investedAmount: 161874,
    currentValue: 78347,
    aiScore: 61,
    peRatio: 18.2,
    pbRatio: 2.4,
    beta: 0.95,
    notes: 'Major drag position (-51.6%). Post-merger margin indigestion and credit-deposit ratio balancing.'
  },
  {
    id: 'hindunilvr',
    symbol: 'HINDUNILVR',
    name: 'Hindustan Unilever Ltd',
    sector: 'FMCG & Consumer',
    marketCap: 'Large',
    investedAmount: 90360,
    currentValue: 70020,
    aiScore: 62,
    peRatio: 54.0,
    pbRatio: 9.8,
    beta: 0.58,
    notes: 'Subdued rural volume recovery and price cuts impacting top-line momentum.'
  },
  {
    id: 'tcs',
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    sector: 'Information Technology',
    marketCap: 'Large',
    investedAmount: 99600,
    currentValue: 66270,
    aiScore: 64,
    peRatio: 28.5,
    pbRatio: 12.1,
    beta: 0.72,
    notes: 'IT services discretionary spend slowdown in US and BFSI verticals.'
  },
  {
    id: 'itc',
    symbol: 'ITC',
    name: 'ITC Ltd',
    sector: 'FMCG & Consumer',
    marketCap: 'Large',
    investedAmount: 85320,
    currentValue: 56419,
    aiScore: 60,
    peRatio: 25.0,
    pbRatio: 6.5,
    beta: 0.65,
    notes: 'Cigarette volume tax headwinds and agri-business cyclical bottom.'
  },
  {
    id: 'infy',
    symbol: 'INFY',
    name: 'Infosys Ltd',
    sector: 'Information Technology',
    marketCap: 'Large',
    investedAmount: 81540,
    currentValue: 55890,
    aiScore: 62,
    peRatio: 24.1,
    pbRatio: 7.2,
    beta: 0.88,
    notes: 'Deal ramp-up delays and wage pressure causing negative returns.'
  },
  {
    id: 'bel',
    symbol: 'BEL',
    name: 'Bharat Electronics Ltd',
    sector: 'Defense & Aerospace',
    marketCap: 'Mid',
    investedAmount: 30600,
    currentValue: 48744,
    aiScore: 64,
    peRatio: 42.0,
    pbRatio: 9.2,
    beta: 1.18,
    notes: 'Strong defense electronics execution with healthy order inflow.'
  },
  {
    id: 'tmcv',
    symbol: 'TMCV',
    name: 'Tata Motors CV / DVR',
    sector: 'Automobile',
    marketCap: 'Mid',
    investedAmount: 79380,
    currentValue: 47952,
    aiScore: 62,
    peRatio: 16.5,
    pbRatio: 2.9,
    beta: 1.35,
    notes: 'Commercial vehicle cyclical downturn and margin contraction.'
  }
];

// Presets for testing and user demo
export const BALANCED_BENCHMARK_HOLDINGS: Holding[] = [
  { id: 'b1', symbol: 'HDFCBANK', name: 'HDFC Bank', sector: 'Banking & Financials', marketCap: 'Large', investedAmount: 300000, currentValue: 340000, aiScore: 82, peRatio: 18.2, pbRatio: 2.4, beta: 0.95 },
  { id: 'b2', symbol: 'ICICIBANK', name: 'ICICI Bank', sector: 'Banking & Financials', marketCap: 'Large', investedAmount: 300000, currentValue: 360000, aiScore: 85, peRatio: 17.5, pbRatio: 2.8, beta: 1.02 },
  { id: 'b3', symbol: 'RELIANCE', name: 'Reliance Industries', sector: 'Conglomerate & Energy', marketCap: 'Large', investedAmount: 350000, currentValue: 390000, aiScore: 80, peRatio: 24.5, pbRatio: 2.1, beta: 0.82 },
  { id: 'b4', symbol: 'TCS', name: 'TCS', sector: 'Information Technology', marketCap: 'Large', investedAmount: 250000, currentValue: 275000, aiScore: 84, peRatio: 28.5, pbRatio: 12.1, beta: 0.72 },
  { id: 'b5', symbol: 'INFY', name: 'Infosys', sector: 'Information Technology', marketCap: 'Large', investedAmount: 220000, currentValue: 245000, aiScore: 81, peRatio: 24.1, pbRatio: 7.2, beta: 0.85 },
  { id: 'b6', symbol: 'LT', name: 'Larsen & Toubro', sector: 'Capital Goods & Infra', marketCap: 'Large', investedAmount: 250000, currentValue: 295000, aiScore: 86, peRatio: 34.1, pbRatio: 4.2, beta: 0.92 },
  { id: 'b7', symbol: 'SUNPHARMA', name: 'Sun Pharma', sector: 'Healthcare & Pharma', marketCap: 'Large', investedAmount: 200000, currentValue: 235000, aiScore: 88, peRatio: 36.2, pbRatio: 5.1, beta: 0.55 },
  { id: 'b8', symbol: 'BHARTIARTL', name: 'Bharti Airtel', sector: 'Telecommunications', marketCap: 'Large', investedAmount: 220000, currentValue: 260000, aiScore: 83, peRatio: 46.2, pbRatio: 5.6, beta: 0.78 },
  { id: 'b9', symbol: 'MARUTI', name: 'Maruti Suzuki', sector: 'Automobile', marketCap: 'Large', investedAmount: 180000, currentValue: 210000, aiScore: 79, peRatio: 27.4, pbRatio: 4.1, beta: 0.85 },
  { id: 'b10', symbol: 'HINDUNILVR', name: 'Hindustan Unilever', sector: 'FMCG & Consumer', marketCap: 'Large', investedAmount: 200000, currentValue: 215000, aiScore: 78, peRatio: 52.0, pbRatio: 9.8, beta: 0.58 }
];
